version: '3'

services:
  app:
    image: matomo:4.5-fpm-alpine
    restart: always
    depends_on:
      - db
    networks:
      - nginx-proxy
    ports:
      - 8080:80
    volumes:
      # - ./config:/var/www/html/config:rw
      # - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
    env_file:
      - ./db.env

  db:
    image: mariadb:10.6
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    env_file:
      - ./db.env

volumes:
  db:
  matomo: